**Задание 1**. Решить систему уравнений методом Гаусса:
$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$

**Решение**

Запишем расширенную матрицу системы:

$\left.\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}\right|\begin{matrix}
\text{*2 (1)}\\ 
\text{вычитаем из 2-й строки 1-ю}\\
{}
\end{matrix}$ 

$\left.\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & -3 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}\right|\begin{matrix}
{}\\ 
{}\\
\text{вычитаем из 3-й строки 1-ю}
\end{matrix}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & -3 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Cистема будет иметь множество решений:

$x_4 = C$

$x_3 = -\frac{4-3C}{2}$

$x_2 = 2-\frac{4-3C}{2}-3C$

$x_1 = -2+\frac{4-3C}{2}+3C-\frac{4-3C}{2}+2C = 5C-2$

**Задание 2**. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [12]:
import numpy as np

def compare_rank(A, b):
    A_ext = np.column_stack([A, b])
    rank_A = np.linalg.matrix_rank(A)
    rank_A_ext = np.linalg.matrix_rank(A_ext)
    n = len(A[0])

    print(f'A:\n{A}\n')
    print(f'A_ext:\n{A_ext}\n')
    print(f'rank(A): {rank_A}\n')
    print(f'rank(A_ext): {rank_A_ext}\n')
    print(f'# of vars: {n}\n')

    if rank_A == rank_A_ext == n:
        print(f'Система совместна и имеет единственное решение.\n')
    elif rank_A == rank_A_ext < n:
        print(f'Система совместна и имеет бесконечное кол-во решений.\n')
    elif rank_A < rank_A_ext:
        print(f'Система несовместна.\n')

In [13]:
print("a)")
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])
compare_rank(A, b)

print("б)")
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5])
compare_rank(A,b)

print("в)")
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2])
compare_rank(A,b)

a)
A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]

A_ext:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

rank(A): 3

rank(A_ext): 3

# of vars: 3

Система совместна и имеет единственное решение.

б)
A:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]

A_ext:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

rank(A): 1

rank(A_ext): 2

# of vars: 3

Система несовместна.

в)
A:
[[ 1  2  5]
 [ 3  1 -8]]

A_ext:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

rank(A): 2

rank(A_ext): 2

# of vars: 3

Система совместна и имеет бесконечное кол-во решений.



**Задание 3**. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей
$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$

In [14]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])
compare_rank(A,b)

A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

A_ext:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

rank(A): 4

rank(A_ext): 4

# of vars: 4

Система совместна и имеет единственное решение.



**Задание 4**. Дана система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Запишем систему в виде расширенной матрицы.
$\left.\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}\right|\begin{matrix}
\text{*2 и вычитаем из 2-ой и 3-ей}\\ 
{}\\
{}
\end{matrix}$ = 
$\left.\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c - 3a
\end{matrix}
\end{pmatrix}\right|\begin{matrix}
{}\\ 
\text{*2 и вычитаем из 3-ей}\\
{}
\end{matrix}$ = 
$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
2 & 1 & 0 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c + a - 2b
\end{matrix}
\end{pmatrix}$

Если $c + a - 2b \neq 0$, то система несовместна.